/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlycuahangmaytinh.view;

/**
 *
 * @author MSI Modern 15
 */
public class DashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel() {
        initComponents();
        loadDemoData();
    }
    private void loadDemoData() {
        // Dữ liệu mẫu tạm để test giao diện (sau này bạn kia thay bằng ProductDAO/InvoiceDAO/CustomerDAO thật)
        lblTotalProducts.setText("Tổng sản phẩm: 10");
        lblTotalCustomers.setText("Tổng khách hàng: 5");
        lblTotalInvoices.setText("Tổng hóa đơn: 3");
        lblTotalRevenue.setText("Tổng doanh thu: 25,300,000 VNĐ");

        javax.swing.table.DefaultTableModel bestSellerModel =
            (javax.swing.table.DefaultTableModel) tblBestSeller.getModel();
        bestSellerModel.addRow(new Object[]{ "SP001", "Dell Latitude 5420", "3" });
        bestSellerModel.addRow(new Object[]{ "SP008", "Samsung SSD 870 EVO 500GB", "2" });

        javax.swing.table.DefaultTableModel lowStockModel =
            (javax.swing.table.DefaultTableModel) tblLowStock.getModel();
        lowStockModel.addRow(new Object[]{ "SP009", "Logitech K120", "2" });
        lowStockModel.addRow(new Object[]{ "SP010", "Logitech M331", "1" });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblTotalProducts = new javax.swing.JLabel();
        lblTotalCustomers = new javax.swing.JLabel();
        lblTotalInvoices = new javax.swing.JLabel();
        lblTotalRevenue = new javax.swing.JLabel();
        lblBestSellerTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBestSeller = new javax.swing.JTable();
        lblLowStockTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLowStock = new javax.swing.JTable();

        lblTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitle.setText("THỐNG KÊ");

        lblTotalProducts.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblTotalProducts.setForeground(new java.awt.Color(25, 35, 55));
        lblTotalProducts.setText("Tổng sản phẩm: 0");

        lblTotalCustomers.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblTotalCustomers.setForeground(new java.awt.Color(25, 35, 55));
        lblTotalCustomers.setText("Tổng khách hàng: 0");

        lblTotalInvoices.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblTotalInvoices.setForeground(new java.awt.Color(25, 35, 55));
        lblTotalInvoices.setText("Tổng hóa đơn: 0");

        lblTotalRevenue.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblTotalRevenue.setForeground(new java.awt.Color(25, 35, 55));
        lblTotalRevenue.setText("Tổng doanh thu: 0");

        lblBestSellerTitle.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblBestSellerTitle.setText("Sản phẩm bán chạy");

        tblBestSeller.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Số lượng đã bán"
            }
        ));
        jScrollPane1.setViewportView(tblBestSeller);

        lblLowStockTitle.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblLowStockTitle.setText("Sản phẩm sắp hết hàng");

        tblLowStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Tồn kho"
            }
        ));
        jScrollPane2.setViewportView(tblLowStock);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitle)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTotalProducts)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblTotalCustomers)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblTotalInvoices)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblTotalRevenue)))
                                .addGap(0, 289, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(lblBestSellerTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLowStockTitle)
                        .addGap(107, 107, 107))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalProducts)
                    .addComponent(lblTotalCustomers)
                    .addComponent(lblTotalInvoices)
                    .addComponent(lblTotalRevenue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBestSellerTitle)
                    .addComponent(lblLowStockTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBestSellerTitle;
    private javax.swing.JLabel lblLowStockTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalCustomers;
    private javax.swing.JLabel lblTotalInvoices;
    private javax.swing.JLabel lblTotalProducts;
    private javax.swing.JLabel lblTotalRevenue;
    private javax.swing.JTable tblBestSeller;
    private javax.swing.JTable tblLowStock;
    // End of variables declaration//GEN-END:variables
}
