/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlycuahangmaytinh.view;

/**
 *
 * @author MSI Modern 15
 */
public class HomeFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeFrame.class.getName());

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
    initComponents();

    // Hiển thị ảnh sản phẩm
    lblImage1.setIcon(resizeImage("/gui/anh1.jpg", 230, 150));
    lblImage2.setIcon(resizeImage("/gui/anh2.jpg", 230, 150));
    lblImage3.setIcon(resizeImage("/gui/anh3.jpg", 230, 150));

    // Căn giữa ảnh
    lblImage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblImage2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblImage3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblStoreName = new javax.swing.JLabel();
        btnProduct = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();
        lblFeatured = new javax.swing.JLabel();
        pnlProducts = new javax.swing.JPanel();
        pnlProduct1 = new javax.swing.JPanel();
        lblImage1 = new javax.swing.JLabel();
        lblProductName1 = new javax.swing.JLabel();
        lblPrice1 = new javax.swing.JLabel();
        lblBrand1 = new javax.swing.JLabel();
        btnDetail1 = new javax.swing.JButton();
        pnlProduct2 = new javax.swing.JPanel();
        lblImage2 = new javax.swing.JLabel();
        lblProductName2 = new javax.swing.JLabel();
        lblBrand2 = new javax.swing.JLabel();
        lblPrice2 = new javax.swing.JLabel();
        btnDetail2 = new javax.swing.JButton();
        pnlProduct3 = new javax.swing.JPanel();
        lblImage3 = new javax.swing.JLabel();
        lblProductName3 = new javax.swing.JLabel();
        lblBrand3 = new javax.swing.JLabel();
        lblPrice3 = new javax.swing.JLabel();
        btnDetail3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHeader.setBackground(new java.awt.Color(25, 35, 55));
        pnlHeader.setPreferredSize(new java.awt.Dimension(1000, 70));

        lblLogo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo.setText("OLDTECH");

        lblStoreName.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblStoreName.setForeground(new java.awt.Color(255, 255, 255));
        lblStoreName.setText("COMPUTER STORE");

        btnProduct.setText("SẢN PHẨM");

        btnLogin.setText("ĐĂNG NHẬP");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblStoreName, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProduct)
                .addGap(91, 91, 91)
                .addComponent(btnLogin)
                .addGap(65, 65, 65))
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStoreName)
                    .addComponent(btnLogin)
                    .addComponent(btnProduct))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlHeader, java.awt.BorderLayout.NORTH);

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setPreferredSize(new java.awt.Dimension(1000, 500));
        pnlContent.setLayout(new java.awt.BorderLayout());

        lblFeatured.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblFeatured.setForeground(new java.awt.Color(25, 35, 55));
        lblFeatured.setText("SẢN PHẨM NỔI BẬT");
        pnlContent.add(lblFeatured, java.awt.BorderLayout.NORTH);

        pnlProducts.setPreferredSize(new java.awt.Dimension(900, 250));

        pnlProduct1.setBackground(new java.awt.Color(255, 255, 255));
        pnlProduct1.setPreferredSize(new java.awt.Dimension(250, 350));

        lblImage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/anh1.jpg"))); // NOI18N
        lblImage1.setPreferredSize(new java.awt.Dimension(230, 150));

        lblProductName1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblProductName1.setText("Dell Latitude 5420");

        lblPrice1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPrice1.setText("9.000.000 VND");

        lblBrand1.setText("Dell");

        btnDetail1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnDetail1.setText("XEM CHI TIẾT");
        btnDetail1.addActionListener(this::btnDetail1ActionPerformed);

        javax.swing.GroupLayout pnlProduct1Layout = new javax.swing.GroupLayout(pnlProduct1);
        pnlProduct1.setLayout(pnlProduct1Layout);
        pnlProduct1Layout.setHorizontalGroup(
            pnlProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProduct1Layout.createSequentialGroup()
                .addGroup(pnlProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProduct1Layout.createSequentialGroup()
                        .addGroup(pnlProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProduct1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(pnlProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBrand1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblProductName1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlProduct1Layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(btnDetail1)))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProduct1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlProduct1Layout.setVerticalGroup(
            pnlProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProduct1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(lblProductName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrice1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBrand1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnDetail1)
                .addContainerGap())
        );

        pnlProducts.add(pnlProduct1);

        pnlProduct2.setBackground(new java.awt.Color(255, 255, 255));
        pnlProduct2.setPreferredSize(new java.awt.Dimension(250, 350));

        lblImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/anh2.jpg"))); // NOI18N
        lblImage2.setPreferredSize(new java.awt.Dimension(230, 150));

        lblProductName2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblProductName2.setText("Samsung 24 inch F24T350");

        lblBrand2.setText("Samsung");

        lblPrice2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPrice2.setText("3.000.000 VNĐ");

        btnDetail2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnDetail2.setText("XEM CHI TIẾT");

        javax.swing.GroupLayout pnlProduct2Layout = new javax.swing.GroupLayout(pnlProduct2);
        pnlProduct2.setLayout(pnlProduct2Layout);
        pnlProduct2Layout.setHorizontalGroup(
            pnlProduct2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProduct2Layout.createSequentialGroup()
                .addGroup(pnlProduct2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProduct2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDetail2))
                    .addGroup(pnlProduct2Layout.createSequentialGroup()
                        .addGroup(pnlProduct2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProduct2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(pnlProduct2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProductName2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBrand2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlProduct2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlProduct2Layout.setVerticalGroup(
            pnlProduct2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProduct2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblProductName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrice2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBrand2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnDetail2)
                .addContainerGap())
        );

        pnlProducts.add(pnlProduct2);

        pnlProduct3.setBackground(new java.awt.Color(255, 255, 255));
        pnlProduct3.setPreferredSize(new java.awt.Dimension(250, 350));

        lblImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/anh3.jpg"))); // NOI18N
        lblImage3.setPreferredSize(new java.awt.Dimension(230, 150));

        lblProductName3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblProductName3.setText("Samsung SSD 870 EVO 500GB");

        lblBrand3.setText("1.300.000 VNĐ");

        lblPrice3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPrice3.setText("Samsung");

        btnDetail3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnDetail3.setText("XEM CHI TIẾT");
        btnDetail3.addActionListener(this::btnDetail3ActionPerformed);

        javax.swing.GroupLayout pnlProduct3Layout = new javax.swing.GroupLayout(pnlProduct3);
        pnlProduct3.setLayout(pnlProduct3Layout);
        pnlProduct3Layout.setHorizontalGroup(
            pnlProduct3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProduct3Layout.createSequentialGroup()
                .addGroup(pnlProduct3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProduct3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProduct3Layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDetail3))
                        .addGroup(pnlProduct3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(pnlProduct3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblProductName3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlProduct3Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(pnlProduct3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblBrand3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(pnlProduct3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlProduct3Layout.setVerticalGroup(
            pnlProduct3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProduct3Layout.createSequentialGroup()
                .addComponent(lblImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(lblProductName3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBrand3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrice3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnDetail3)
                .addContainerGap())
        );

        pnlProducts.add(pnlProduct3);

        pnlContent.add(pnlProducts, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private javax.swing.ImageIcon resizeImage(String imagePath, int maxWidth, int maxHeight) {
    java.net.URL imageURL = getClass().getResource(imagePath);

    if (imageURL == null) {
        System.out.println("Không tìm thấy ảnh: " + imagePath);
        return null;
    }

    javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(imageURL);

    java.awt.Image originalImage = originalIcon.getImage();

    int originalWidth = originalImage.getWidth(null);
    int originalHeight = originalImage.getHeight(null);

    double widthRatio = (double) maxWidth / originalWidth;
    double heightRatio = (double) maxHeight / originalHeight;

    double ratio = Math.min(widthRatio, heightRatio);

    int newWidth = (int) (originalWidth * ratio);
    int newHeight = (int) (originalHeight * ratio);

    java.awt.Image resizedImage = originalImage.getScaledInstance(
        newWidth,
        newHeight,
        java.awt.Image.SCALE_SMOOTH
    );

    return new javax.swing.ImageIcon(resizedImage);
}
    private void btnDetail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetail1ActionPerformed
    
    private void btnDetail3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetail3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetail3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeFrame().setVisible(true));
    }
    public javax.swing.JPanel getFeaturedPanel() {
        return pnlContent;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetail1;
    private javax.swing.JButton btnDetail2;
    private javax.swing.JButton btnDetail3;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnProduct;
    private javax.swing.JLabel lblBrand1;
    private javax.swing.JLabel lblBrand2;
    private javax.swing.JLabel lblBrand3;
    private javax.swing.JLabel lblFeatured;
    private javax.swing.JLabel lblImage1;
    private javax.swing.JLabel lblImage2;
    private javax.swing.JLabel lblImage3;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPrice1;
    private javax.swing.JLabel lblPrice2;
    private javax.swing.JLabel lblPrice3;
    private javax.swing.JLabel lblProductName1;
    private javax.swing.JLabel lblProductName2;
    private javax.swing.JLabel lblProductName3;
    private javax.swing.JLabel lblStoreName;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlProduct1;
    private javax.swing.JPanel pnlProduct2;
    private javax.swing.JPanel pnlProduct3;
    private javax.swing.JPanel pnlProducts;
    // End of variables declaration//GEN-END:variables
}
