/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlycuahangmaytinh.view;

/**
 *
 * @author MSI Modern 15
 */
public class InvoicePanel extends javax.swing.JPanel {

    /**
     * Creates new form InvoicePanel
     */
    private final java.util.Map<String, String[][]> demoInvoiceDetails = new java.util.HashMap<>();
    public InvoicePanel() {
        initComponents();
        // Dữ liệu mẫu tạm để test giao diện (sau này bạn kia thay bằng InvoiceDAO)
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) tblInvoices.getModel();
    model.addRow(new Object[]{ "HD001", "15/08/2026", "Nguyễn Văn A", "nv001", "9,000,000" });

    demoInvoiceDetails.put("HD001", new String[][] {
        { "SP001", "Dell Latitude 5420", "9,000,000", "1", "9,000,000" }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnViewDetail = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInvoices = new javax.swing.JTable();

        lblTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitle.setText("DANH SÁCH HÓA ĐƠN");

        lblSearch.setText("Tìm kiếm:");

        btnSearch.setText("Tìm");

        btnViewDetail.setText("Xem chi tiết");
        btnViewDetail.addActionListener(this::btnViewDetailActionPerformed);

        tblInvoices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Ngày lập", "Khách hàng", "Nhân viên", "Tổng tiền"
            }
        ));
        jScrollPane1.setViewportView(tblInvoices);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSearch)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnViewDetail)
                                    .addComponent(btnSearch))))
                        .addContainerGap(101, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewDetail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailActionPerformed
        // TODO add your handling code here:
        int row = tblInvoices.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Vui lòng chọn 1 hóa đơn trong bảng để xem chi tiết.");
            return;
        }

        String invoiceId = tblInvoices.getValueAt(row, 0).toString();
        String date = tblInvoices.getValueAt(row, 1).toString();
        String customer = tblInvoices.getValueAt(row, 2).toString();
        String staff = tblInvoices.getValueAt(row, 3).toString();
        String total = tblInvoices.getValueAt(row, 4).toString();

        com.mycompany.quanlycuahangmaytinh.view.InvoiceDetailDialog dialog = new com.mycompany.quanlycuahangmaytinh.view.InvoiceDetailDialog(
            (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
            true
        );
        dialog.loadInvoiceData(invoiceId, date, customer, staff, total);

        String[][] details = demoInvoiceDetails.get(invoiceId);
        if (details != null) {
            for (String[] line : details) {
                dialog.addDetailRow(line[0], line[1], line[2], line[3], line[4]);
            }
        }

        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnViewDetailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewDetail;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblInvoices;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
