/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlycuahangmaytinh.view;

/**
 *
 * @author MSI Modern 15
 */
public class SalesPanel extends javax.swing.JPanel {

    /**
     * Creates new form SalesPanel
     */
    private final java.util.Map<String, Integer> demoPrices = new java.util.HashMap<>();
    public SalesPanel() {
        initComponents();
        demoPrices.put("SP001 - Dell Latitude 5420", 9000000);
        demoPrices.put("SP005 - Samsung 24 inch F24T350", 3000000);
        demoPrices.put("SP008 - Samsung SSD 870 EVO 500GB", 1300000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCustomer = new javax.swing.JLabel();
        cboCustomer = new javax.swing.JComboBox<>();
        lblProduct = new javax.swing.JLabel();
        cboProduct = new javax.swing.JComboBox<>();
        lblQty = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        btnAddToCart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        btnRemoveFromCart = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        btnSaveInvoice = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitle.setText("BÁN HÀNG");

        lblCustomer.setText("Khách hàng:");

        cboCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khách lẻ", "Nguyễn Văn A", "Trần Thị B" }));

        lblProduct.setText("Sản phẩm:");

        cboProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SP001 - Dell Latitude 5420", "SP005 - Samsung 24 inch F24T350", "SP008 - Samsung SSD 870 EVO 500GB" }));

        lblQty.setText("Số lượng:");

        btnAddToCart.setText("Thêm vào giỏ");
        btnAddToCart.addActionListener(this::btnAddToCartActionPerformed);

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Đơn giá", "Số lượng", "Thành tiền"
            }
        ));
        jScrollPane1.setViewportView(tblCart);

        btnRemoveFromCart.setText("Xóa khỏi giỏ");
        btnRemoveFromCart.addActionListener(this::btnRemoveFromCartActionPerformed);

        lblTotal.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(180, 0, 0));
        lblTotal.setText("Tổng tiền: 0 VND");

        btnSaveInvoice.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnSaveInvoice.setText("Lưu hóa đơn");
        btnSaveInvoice.addActionListener(this::btnSaveInvoiceActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCustomer)
                                    .addComponent(lblProduct)
                                    .addComponent(lblQty))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAddToCart)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnRemoveFromCart))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotal)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveInvoice)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCustomer)
                    .addComponent(cboCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProduct)
                    .addComponent(cboProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQty)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAddToCart)
                        .addComponent(btnRemoveFromCart)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(btnSaveInvoice))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        // TODO add your handling code here:
        String product = (String) cboProduct.getSelectedItem();
        if (product == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm.");
            return;
        }

        int quantity;
        try {
            quantity = Integer.parseInt(txtQty.getText().trim());
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Số lượng phải là số nguyên hợp lệ.");
            return;
        }

        if (quantity <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0.");
            return;
        }

        String id = product.split(" - ")[0];
        String name = product.split(" - ")[1];
        int price = demoPrices.getOrDefault(product, 0);
        int lineTotal = price * quantity;

        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) tblCart.getModel();
        model.addRow(new Object[]{ id, name, price, quantity, lineTotal });

        txtQty.setText("");
        updateTotal();
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void btnRemoveFromCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveFromCartActionPerformed
        // TODO add your handling code here:
        int row = tblCart.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Vui lòng chọn 1 sản phẩm trong giỏ hàng để xóa.");
            return;
        }

        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) tblCart.getModel();
        model.removeRow(row);
        updateTotal();
    }//GEN-LAST:event_btnRemoveFromCartActionPerformed

    private void btnSaveInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveInvoiceActionPerformed
        // TODO add your handling code here:
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) tblCart.getModel();

        if (model.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Giỏ hàng đang trống, vui lòng thêm sản phẩm trước khi lưu hóa đơn.");
            return;
        }

        String customer = (String) cboCustomer.getSelectedItem();
        if (customer == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Vui lòng chọn khách hàng.");
            return;
        }

        // TODO: Bạn kia sẽ nối code lưu hóa đơn thật vào đây:
        // - Tạo đối tượng Invoice/OrderDetail
        // - Gọi InvoiceDAO.save(...) / OrderDAO.save(...)
        // - Gọi ProductDAO.updateQuantity(...) để giảm tồn kho (FR-13)

        javax.swing.JOptionPane.showMessageDialog(this,
            "Đã xác nhận hóa đơn (demo). Chức năng lưu vào cơ sở dữ liệu sẽ được hoàn thiện sau.");

        // Reset giỏ hàng sau khi lưu (demo)
        model.setRowCount(0);
        updateTotal();
    }//GEN-LAST:event_btnSaveInvoiceActionPerformed
    private void updateTotal() {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) tblCart.getModel();

        long total = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            Object value = model.getValueAt(i, 4); // cột "Thành tiền"
            if (value != null) {
                total += Long.parseLong(value.toString());
            }
        }

        lblTotal.setText("Tổng tiền: " + String.format("%,d", total) + " VNĐ");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnRemoveFromCart;
    private javax.swing.JButton btnSaveInvoice;
    private javax.swing.JComboBox<String> cboCustomer;
    private javax.swing.JComboBox<String> cboProduct;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblCart;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables
}

